import {createHash} from "node:crypto";
import {readFile,realpath,stat} from "node:fs/promises";
import {execFile} from "node:child_process";
import {promisify} from "node:util";
import {resolve,relative,isAbsolute,sep} from "node:path";
import {validateSpecKitContract,type SpecKitArtifactContract} from "./spec-kit-contract.js";
import {preflightSkills,type SkillPreflightOptions} from "./skill-preflight.js";

export type OriginalSDDStage="constitution"|"specify"|"clarify"|"plan"|"checklist"|"tasks"|"analyze";
export interface PredevelopmentPolicy{
  clarify:boolean;checklist:boolean;analyze:boolean;
}
export interface OriginalStageProof{
  stage:OriginalSDDStage;
  actor:"main_agent"|"reviewer";
  /** Exact approved source snapshot, NOT a model's invented stage result. */
  commit:string;
  /** Identifies a trusted reviewed host event, never auto-generated by a model. */
  sourceRef:string;
  files:string[];
  result:"passed"|"needs_revision";
}
export interface SDDQualityFinding{
  fromStage:OriginalSDDStage;
  target:"specify"|"plan"|"tasks";
  severity:"critical"|"major"|"minor";
  resolved:boolean;
  detail:string;
}
export interface PredevelopmentDecision {
  nextStage:OriginalSDDStage|null;
  nextOriginalSkill:string|null;
  readyForIntakeApproval:boolean;
  blocked:string[];
  returnToStage?:"specify"|"plan"|"tasks";
  completed:OriginalSDDStage[];
  skipped:OriginalSDDStage[];
}
export type TrustedStageVerifier=(evidence:OriginalStageProof,
  expected:{stage:OriginalSDDStage;commit:string})=>Promise<boolean>;
const stages:OriginalSDDStage[]=["constitution","specify","clarify",
  "plan","checklist","tasks","analyze"];
const git=promisify(execFile);
const canonical:Record<OriginalSDDStage,string[]>={
  constitution:[".specify/memory/constitution.md"],
  specify:["spec"],clarify:["spec"],plan:["plan"],
  checklist:["checklist"],tasks:["tasks"],
  analyze:["spec","plan","tasks"],
};
function expectedFiles(stage:OriginalSDDStage,c:SpecKitArtifactContract):string[] {
  return canonical[stage].map(key=>key==="checklist"
    ? Object.entries(c.artifacts).filter(([name])=>name==="checklist").map(([,path])=>path)[0]??""
    :key==="spec"||key==="plan"||key==="tasks"
      ? c.artifacts[key]??"":key);
}
async function verifySnapshot(root:string,proof:OriginalStageProof):Promise<void>{
  const rr=await realpath(root);
  for(const path of proof.files) {
    if(!path || path.startsWith("/")||path.includes("\\")||
      path.split("/").some(x=>x==="."||x===".."||!x))
      throw new Error("Unsafe original Spec Kit stage artifact path");
    const full=await realpath(resolve(rr,path));
    const rel=relative(rr,full);
    if(!rel||rel===".."||rel.startsWith(".."+sep)||isAbsolute(rel)||
        !(await stat(full)).isFile())
      throw new Error("Spec Kit stage artifact escapes project worktree");
    let old:Buffer;
    try {
      old=(await git("git",["-C",rr,"show",proof.commit+":"+path],
        {encoding:"buffer",timeout:15000,maxBuffer:8*1024*1024})).stdout;
    } catch {throw new Error("Original stage evidence missing at exact Git SHA");}
    if(!old.equals(await readFile(full)))
      throw new Error("Original stage artifact drift from recorded Git SHA");
  }
}
export async function inspectSpecKitPredevelopment(
  root:string,candidate:SpecKitArtifactContract,
  policy:PredevelopmentPolicy,
  proofs:OriginalStageProof[],
  verifyStage:TrustedStageVerifier,
  skillOptions:SkillPreflightOptions,
  findings:SDDQualityFinding[]=[],
):Promise<PredevelopmentDecision> {
  const contract=validateSpecKitContract(candidate);
  if(contract.scenario!=="feature")
    throw new Error("Feature/change predevelopment needs original Spec Kit feature artifacts");
  if(!policy || [policy.clarify,policy.checklist,policy.analyze].some(x=>typeof x!=="boolean"))
    throw new Error("Invalid optional original Spec Kit gate policy");
  if(!Array.isArray(proofs)||!Array.isArray(findings)||!verifyStage)
    throw new Error("Missing trusted stage evidence/verifier");
  const expectedStages=stages.filter(s=>
    !["clarify","checklist","analyze"].includes(s) ||
    s==="clarify"&&policy.clarify ||
    s==="checklist"&&policy.checklist ||
    s==="analyze"&&policy.analyze);
  const skipped=stages.filter(x=>!expectedStages.includes(x));
  const completed:OriginalSDDStage[]=[];
  if(findings.some(x=>!x||!["specify","plan","tasks"].includes(x.target)||
      !["critical","major","minor"].includes(x.severity)||
      !["constitution","specify","clarify","plan","checklist","tasks","analyze"].includes(x.fromStage)))
    throw new Error("Invalid Spec Kit quality finding");
  const unresolved=findings.filter(x=>!x.resolved && ["critical","major"].includes(x.severity));
  const first=unresolved.sort((a,b)=>
    ["specify","plan","tasks"].indexOf(a.target)-
    ["specify","plan","tasks"].indexOf(b.target))[0];
  if(first) {
    const target=first.target;
    return {nextStage:target,nextOriginalSkill:"speckit-"+target,
      readyForIntakeApproval:false,blocked:["Unresolved "+first.severity+
        " quality gap: return to original "+target+" stage"],
      returnToStage:target,completed,skipped};
  }
  if(new Set(proofs.map(x=>x.stage)).size!==proofs.length)
    throw new Error("Duplicate original Spec Kit stage result");
  if(proofs.length>expectedStages.length || proofs.some((proof,i)=>
    proof.stage!==expectedStages[i]))
    throw new Error("Original Spec Kit stage proofs must be ordered and cannot skip mandatory stages");
  for(const stage of expectedStages){
    // The skill itself MUST be the upstream original, with exact pinned bytes.
    await preflightSkills({phase:"planning",role:"main_agent",selected:[],
      required:[],off:[],specKitStage:stage},skillOptions);
    const proof=proofs.find(x=>x.stage===stage);
    if(!proof)return {nextStage:stage,nextOriginalSkill:"speckit-"+stage,
      readyForIntakeApproval:false,blocked:[],completed,skipped};
    if(!/^[a-f0-9]{40}$/.test(proof.commit) ||
        !/^[a-zA-Z0-9._:-]{6,120}$/.test(proof.sourceRef) ||
        proof.result!=="passed" ||
        proof.actor!==(stage==="checklist"?"reviewer":"main_agent") ||
        JSON.stringify(proof.files)!==JSON.stringify(expectedFiles(stage,contract)) ||
        proof.files.some(x=>!x))
      throw new Error("Original Spec Kit stage evidence does not match reviewed stage");
    await verifySnapshot(root,proof);
    if(!await verifyStage(proof,{stage,commit:proof.commit}))
      throw new Error("Original Spec Kit stage result not trusted by Main Agent");
    if(stage==="constitution"){
      const constitution=await readFile(resolve(root,proof.files[0]!),"utf8");
      if(constitution.includes("[PROJECT_NAME]") ||
          constitution.includes("[PRINCIPLE_1_NAME]"))
        throw new Error("Project Constitution is unratified original placeholder");
    }
    completed.push(stage);
  }
  // No implicit implementation: separately require actual owner approval from #142.
  return {nextStage:null,nextOriginalSkill:null,readyForIntakeApproval:true,
    blocked:[],completed,skipped};
}
